### ISSUE TITLE
建议增加动态显示和隐藏二级文档树的开关

### ISSUE THREAD

**Issue by wish5115** [Misuzu2027/syplugin-dual-doc-list#1]
感谢大佬的插件！👍

建议增加动态显示和隐藏二级文档树的开关，即当打开开关时才开启二级文档树。

现在想关闭二级文档树时需要去插件里关闭，很不方便。

**Comment by Misuzu2027** [comment]
开关的位置是否有推荐，打算放在文档树的更多中，这样干扰较少，不过需要点开一次。
![image](https://github.com/user-attachments/assets/b4b07e94-f9b6-4c73-a82b-ce510a839278)

**Comment by wish5115** [comment]
我觉得可以放到这里，一个开/关图标（不过放更多里也行）

![image](https://github.com/user-attachments/assets/edde09e5-0517-41ff-833c-9837993490f3)

**Comment by Misuzu2027** [comment]
开关看上去还是有些突兀，
![image](https://github.com/user-attachments/assets/0cd1d4a7-f439-4bd6-9204-7dea4c2f0aa8)


放更多里吧，点击切换显示隐藏状态。
![image](https://github.com/user-attachments/assets/eaace4c3-0638-4f5f-9113-20938a533944)

**Comment by wish5115** [comment]
我说的是图标，不是这个开关控件，比如

<img width="407" alt="image" src="https://github.com/user-attachments/assets/0eddd04f-cfdf-41e6-b730-e8e58f10bc07">

不过这个感觉也没那么重要，有就行，看你喜好，用图标会稍微麻烦些。

**Comment by Misuzu2027** [comment]
没看仔细 😂，集市已经更新 v0.0.3版本，可以在更多中切换了。

**Comment by wish5115** [comment]
嗯嗯，已看到。

大佬牛叉👍，效率好高👍
