### ISSUE TITLE
原生实现功能，左边原文档树中全是文件夹，右边docker面板中全是文档

### ISSUE THREAD

**Issue by pisceswb** [Misuzu2027/syplugin-dual-doc-list#11]
请问大佬能否在该插件中原生实现左边原文档树中全是文件夹，右边docker面板中全是文档。
再结合一个左侧原文档树上点击，打开文档并展开子文档树（文件夹显示在左侧，文档显示在右侧）功能。
点击原文档树和docker面板上的定位按钮，能否使原文档树和docker面板都能够正常定位到文档。
谢谢大佬！
代码及想法来源：https://ld246.com/article/1728920432672

`/* 隐藏二级文档列表含有子文档的文档 */
.misuzu2027__doc-list li[data-type="navigation-file"][data-count]:not([data-count="0"]){
    display:none;
}
​
/*隐藏一级文档树的单文档 */
.file-tree.sy__file li[data-type="navigation-file"][data-count][data-count="0"]{
display:none;
}

​
/* 二级文档树的文件夹用高亮 icon 标识 */

.misuzu2027__doc-list li[data-type="navigation-file"][data-count]:not([data-count="0"]) span:first-of-type{
  background-image: linear-gradient(to top, #a8edea 0%, #fed6e3 100%);
}

// js代码左键点击展开文档树 

let g_reset = setInterval(main, 2000);

function main() {
    if (document.querySelector('.sy__file')) {
        clearInterval(g_reset);
    }else{
        return false;
    }
    document.querySelector('.sy__file').addEventListener('mousedown', event => {
        if (event.button != 0) return;
        event.preventDefault();
        if (!event.target.classList.contains('b3-list-item__text')) return;
        if (event.target.parentNode.getAttribute("data-type") !== "navigation-file") return;
        const b3ListItemToggle = event.target.parentNode.querySelector('.b3-list-item__toggle');
        if (b3ListItemToggle.classList.contains('fn__hidden')) return;
        b3ListItemToggle.click();
    });
}

`

**Comment by Misuzu2027** [comment]
1. > 原文档树中全是文件夹
  * 我个人不喜欢在插件中修改系统原生的东西，因为可能会跟其他插件冲突。
  * 虽然我们一般对文档是否有子文档来判断是否是文件夹，但是思源本身没有文件夹的概念，所以比较冲突，我不太想制定自己的标准。
2. > 二级文档列表全是文档
  *  理由同上，思源本身是没有文件夹概念的，有些“文件夹”可能也写有需要检索的信息。
3.  > 再结合一个左侧原文档树上点击，打开文档并展开子文档树（文件夹显示在左侧，文档显示在右侧）功能。
  * 有些插件好像是提供了单击有子文档的文档，会展开子文档。配合隐藏的 css 应该也差不多。
4. > 点击原文档树和docker面板上的定位按钮，能否使原文档树和docker面板都能够正常定位到文档。
  * 这个还是需要区分开的，添加二级文档列表的定位功能，就是为了不打乱文档树，如果文档过多或层级过深，文档树展开后一点也不美观。
  * 不过可以自己写 js ，给按钮添加点击事件，点任意一个按钮，让代码同时点击另一个按钮。
