### ISSUE TITLE
bug 更新到最新版本后，dock失效了。

### ISSUE THREAD

**Issue by luluciamk** [Misuzu2027/syplugin-dual-doc-list#12]
大大，最新版本更新了什么功能？
思源是最新版，这个插件也是最新版
 
![捕获](https://github.com/user-attachments/assets/a6296295-038f-4350-bf28-4dd82d6c7bec)

结果变成现在这个样子了

**Comment by Misuzu2027** [comment]
v0.0.12 已修复
