### ISSUE TITLE
功能需求：二级文档树变成dock部件

### ISSUE THREAD

**Issue by luluciamk** [Misuzu2027/syplugin-dual-doc-list#4]
参考上个issue，这里重开一个，只是帮助大大分辨。
在
1二级文档树变dock部件
2二级文档树增加独立拖拽宽度
这两个选择中，我个人还是更倾向于前者。
另，在另一个issue中所说

> 在二级文档列表dock折叠状态下，是否需要跟随切换路径？我个人偏向折叠状态下不切换
这种方案我觉得挺好。
本质就是通过一级文档来切换，二级文档来展现。

**Comment by Misuzu2027** [comment]
v0.0.8 已支持 二级文档列表Dock。同时 嵌入的二级文档列表 支持拖拽调整宽度。
