### ISSUE TITLE
功能添加：二级文档书可以增加一个“新建文档”的功能吗？

### ISSUE THREAD

**Issue by luluciamk** [Misuzu2027/syplugin-dual-doc-list#5]
如图
一级文档树有两种新建文档。
A右键选择新建同级文档，B直接点击文档树上的添加按钮，新建子级文档。
![image](https://github.com/user-attachments/assets/135b2feb-1cfa-4a2e-8913-3ed5a4878a29)
我的想法是——
1. A这种操作有点繁琐，在一级树上很少这么做，基本都是用B来嵌套，需要调整层级时一向都是直接拖动。
2. 二级文档树现在只有A这种操作，同样繁琐累人，所以可否增加一个类似“＋”的按钮来新建文档？
3. 一级文档树的新建用于嵌套文档，二级文档树的新建，则负责新建平级文档（毕竟二级树就是为了平级呈现）

**Comment by Misuzu2027** [comment]
可以给文档标题增加 “+“ 按钮，用来新建同级文档

**Comment by Misuzu2027** [comment]
v0.0.8 已支持添加同级文档。

**Comment by luluciamk** [comment]
大大，这个功能设计在哪里？我更新到0.0.9，二级文档树也没有看到类似的按钮

**Comment by luluciamk** [comment]
好了， 大大不用回复，我看到这个“＋”号在哪里了😁
