### ISSUE TITLE
功能添加：可以在二级文档树拖动文档吗？自定义排序功能的延伸

### ISSUE THREAD

**Issue by luluciamk** [Misuzu2027/syplugin-dual-doc-list#6]
不管是一级树还是二级树，我常用的都是“自定义排序”，可是在二级树中并不能做到二级树文档的自由拖动排序，目前我还得是回到一级树，在一级树的子文档自由排序后，刷新二级树使其呈现。
除此之外，二级树倒是能实现其他类型的排序效果。

![image](https://github.com/user-attachments/assets/1956d82d-a5f4-4b0d-837f-3275f2ce7564)
灵，二级文档树上方有三个大大的按钮，话说我感觉有点太扎眼，要是能用更简洁的标志设定或许更美观一点。
类似这种直线开关式样，整体都小一点低调一点。

嗯，这次又是以二级树来强行覆盖一级树的功能，不清楚大大能否做到，希望这个不是太困难的问题。😂

**Comment by Misuzu2027** [comment]
二级文档列表不会添加拖拽功能，原因是拖拽的功能点太多了，动起来非常复杂。

**Comment by luluciamk** [comment]
OK，收到，这个功能有的话更方便，没有的话，只有一点点影响，可以克服。😁
