### ISSUE TITLE
界面美化：二级文档树头顶三枚开关样式可以重新设计吗？

### ISSUE THREAD

**Issue by luluciamk** [Misuzu2027/syplugin-dual-doc-list#7]
![image](https://github.com/user-attachments/assets/fbccefda-d4d9-4132-9d1b-a0bec6a66bb4)
如图，这三枚开关放在此处，无论如何有点扎眼和累赘感（我个人有点强迫症😂），不过这三个开关也真是有用
思索好久，想出一个解决办法，供大大参考
我的想法是——
大大可以把这三枚开关的功能集成到其各自对应的icon图标上吗？

详细说明一下。
即取消掉这三枚开关，当需要开启这三个功能时，点击其对应的icon图标
平时这三个icon默认是一种颜色A（关闭状态）
当需要使用其中一种时，点击对应的icon，这个图标变成另一种颜色B（表示开启）
如果需要关闭，再度点击这个图标关闭就行了。（图标变回颜色A）

这个方案我觉得应该比现在的三个开关设计简洁些，希望大大考虑一下。

**Comment by luluciamk** [comment]
另，还有最后一个图标，这个双文档叠加在一起的icon，之前好像是“复制”的含义，换成“箭头”或者“文件夹”之类的会不会好一点
例如
![R-C](https://github.com/user-attachments/assets/74b8fd08-5a73-4ae2-bc68-762240850a09)
 或者
![252a54de_E776297_69cf2d91](https://github.com/user-attachments/assets/015b465d-3d8d-477f-9acf-5f85d49f90d7)
当然，这是我吹毛求疵，就是有点感觉最后一个图标并不准确，这个对实际操作影响不大。

**Comment by Misuzu2027** [comment]
可以优化，但是颜色区的话感觉不太好，比如一个颜色在亮色模式下还好，在暗黑模式下就会有些突兀，而且不同主题也会有不同的颜色风格，所以界面的一些颜色，会劲量弄成默认颜色。

前两个带锁的图标，可以在不锁定的状态去掉右下角的锁，不过需要花些时间制作svg图标。子文档那个不太好办，本身就没有锁，如果有合适区分状态的图标，可以告知一声，最好是有 svg 格式的。

**Comment by luluciamk** [comment]
大大，意思是一个开关用两种状态式样的svg来表示吗？（希望我没有理解错误）
我找了最后“展开子文档”的两个图标，供你参考。
![开启](https://github.com/user-attachments/assets/06b18f1a-7335-4261-914c-14c1d5b55256)
  
![关闭](https://github.com/user-attachments/assets/63b40e25-05e1-4735-91f2-e9df051a9ba6)

**Comment by luluciamk** [comment]
这是另一种，以文件夹形式为状态的参考
![文件夹关闭](https://github.com/user-attachments/assets/a7f11ef1-2251-4c66-8cf0-24faee908e1c)
 
![文件夹开启3](https://github.com/user-attachments/assets/a166035e-8c84-4711-b972-533bdd5b0b01)
![文件夹开启2](https://github.com/user-attachments/assets/677acc26-e1b1-4798-bf70-62b05ec6b8ce)

**Comment by luluciamk** [comment]
这是另一种，以文件夹形式为状态的参考
![文件夹关闭](https://github.com/user-attachments/assets/e8ca5653-bceb-4af6-84a2-fa24e20eeb2d)
![文件夹开启2](https://github.com/user-attachments/assets/5f7e2b27-9715-4c00-8ff4-8772a0feeda3)
![文件夹开启3](https://github.com/user-attachments/assets/04847dfb-e945-4dbb-9cc0-466b6a01d71f)

**Comment by luluciamk** [comment]
这是另一种，以文件夹形式为状态的参考
![文件夹关闭](https://github.com/user-attachments/assets/d8e64f2d-665f-4ee8-a51e-2dccd54da7b3)

**Comment by luluciamk** [comment]
![文件夹开启2](https://github.com/user-attachments/assets/f6814a48-e003-4775-aff6-50d56fd49e77)
![文件夹开启3](https://github.com/user-attachments/assets/fd706cfa-ffce-4ed4-9196-2d625f0504b3)

**Comment by luluciamk** [comment]
![文件夹开启3](https://github.com/user-attachments/assets/b2bcb52d-57a4-4344-b5c2-de7964922916)

**Comment by luluciamk** [comment]
![文件夹开启2](https://github.com/user-attachments/assets/d8f76505-45ca-4dc9-bb24-a3c64a0d0e04)

**Comment by luluciamk** [comment]
另一种，是文件夹版本的svg
![folder关闭](https://github.com/user-attachments/assets/37774d73-ed52-4d0d-97b0-fa5ba9fe2c79)
![folder开启](https://github.com/user-attachments/assets/9995388e-e869-4b09-b71a-f6010bbbf0f0)
![folder开启2](https://github.com/user-attachments/assets/104f055d-e8de-41c0-9e50-101f517afd34)
![folder开启3](https://github.com/user-attachments/assets/ec07a886-98f5-42c2-8eda-d3facfe9635b)
![folder开启4](https://github.com/user-attachments/assets/1bd312c7-e370-44d7-808f-6bdbe2cedb98)

**Comment by Misuzu2027** [comment]
试了一下，感觉替换图标来表示状态的方式，视觉上区别不大，还是得加背景色，可以看看图标或选中背景颜色上有没有优化建议。
按钮依次是 锁定路径、锁定排序、显示子文档的子文档、使用全文查询。
明亮模式下
未选中 ：
![image](https://github.com/user-attachments/assets/cc883acc-e852-4b65-a819-5f82adc27091)
选中：
![image](https://github.com/user-attachments/assets/a5f540c1-58a7-41d2-b474-c4977b1556a1)

暗黑模式下
未选中：
![image](https://github.com/user-attachments/assets/8ae0a38c-f86f-4f17-a2fe-dc2d178434aa)
选中：
![image](https://github.com/user-attachments/assets/9de798e8-5aa0-4009-8b2a-e6ddc556f635)
