### ISSUE TITLE
新思源版本中docker面板不能自动显示

### ISSUE THREAD

**Issue by pisceswb** [Misuzu2027/syplugin-dual-doc-list#9]
在思源[3.1.10 版-dev1](https://github.com/siyuan-note/siyuan/tree/v3.1.10-dev1)版本中，重新打开思源笔记后，二级文档列表docker面板不能自动显示。
![image](https://github.com/user-attachments/assets/d6e6d50b-5477-4d58-add9-9097694b8e69)

**Comment by Misuzu2027** [comment]
目前不会对预览版本做测试，后续更新 3.1.10 正式版了会再看看存不存在此问题。

**Comment by Misuzu2027** [comment]
更新 思源 3.1.10 后，插件面板是正常的，
